version: '3'

services:
  employee-db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=employee_database
    ports:
      - 5432:5432
